### ISSUE TITLE
"TypeError"

### ISSUE THREAD

**Issue by Abdul-Mueed** [kwongj/roary2fripan#3]
I tried running the script with the basic input and got this message:

"['hypothetical protein', '1', '1', '1', 'NKNGPPGD_00723', '*', '*', '*']
['hypothetical protein', '1', '1', '1', 'NKNGPPGD_00724', '', '', '']
['hypothetical protein', '1', '1', '1', 'NKNGPPGD_00724', '*', '*', '*']
Traceback (most recent call last):
  File "roary2fripan.py", line 72, in <module>
    out.writerows(portho)
TypeError: a bytes-like object is required, not 'str'
"

how do I get it to work?

**Comment by kwongj** [comment]
Sorry for the delay @Abdul-Mueed - can you check whether you are still getting this error with the latest version?

**Comment by Abdul-Mueed** [comment]
Thank you for replying :) 

Since then, my pc crashed and I had to reinstall everything. However, this time running the script gives this output: 

$ python roary2fripan.py -h
 
 File "roary2fripan.py", line 14
    print(*args, file=sys.stderr, **kwargs)
          ^
SyntaxError: invalid syntax

**Comment by Abdul-Mueed** [comment]
same problem as this:
https://github.com/kwongj/roary2fripan/issues/4

**Comment by kwongj** [comment]
You now need Python 3 (python 2 won't be maintained from 2020 onwards).

1. If you have python 3 installed, you can just do:
`python3 roary2fripan.py -h`

2. If you don't want to install python 3, you can download the older release `v0.2-beta`

**Comment by Abdul-Mueed** [comment]
Ah! It works!

Thanks!
:D 

Let me check to see if I get the old error again.

**Comment by Abdul-Mueed** [comment]
"$ python3 roary2fripan.py vibrio_fluvialis

Writing vibrio_fluvialis.proteinortho ... 
Writing vibrio_fluvialis.descriptions ... 
Writing vibrio_fluvialis.strains ... 
Done."

Works fine now!

Thanks!
